# Generated by Django 4.2.4 on 2023-08-25 17:02

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunat', '0003_padron_actividad_economica_padron_comprobantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='padron',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
